CREATE TABLE IF NOT EXISTS public.carrinho
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    precound money,
    quantidade integer,
    amount numeric,
    total numeric,
    taxa numeric,
    produto_nomeprod character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT carrinho_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nomecat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    taxa numeric,
    CONSTRAINT categorias_pkey PRIMARY KEY (nomecat)
);

CREATE TABLE IF NOT EXISTS public.historico
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    precound money,
    quantidade integer,
    amount numeric,
    total numeric,
    taxa numeric,
    produto_nomeprod character varying(100) COLLATE pg_catalog."default",
    id_compra integer,
    date character varying COLLATE pg_catalog."default",
    CONSTRAINT historico_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nomeprod character varying(100) COLLATE pg_catalog."default" NOT NULL,
    preco numeric,
    quantidade integer,
    categoria_nomecat character varying COLLATE pg_catalog."default",
    CONSTRAINT produtos_pkey PRIMARY KEY (nomeprod)
);

ALTER TABLE IF EXISTS public.carrinho
    ADD CONSTRAINT carrinhoprod_fkey FOREIGN KEY (produto_nomeprod)
    REFERENCES public.produtos (nomeprod) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT prodcat_fkey FOREIGN KEY (categoria_nomecat)
    REFERENCES public.categorias (nomecat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;